@startuml 
title Диаграмма контекста
!include ./uml-lib/C4_Context.puml 
' Пользователи
Person(user, "Клиент", "Клиент банка")
Person(backManager, "Менеджер бэк-офиса")
Person(frontManager, "Менеджер фронт-офиса")
Person(operator, "Оператор кол-центра")
Person(partnerOperator, "Оператор партнерского кол-центра")
' Системы
System(ABS, "АБС", "Автоматическая банковская система")
System(ebank, "Интернет-банк", "Онлайн банк")
System(site, "Сайт", "Сайт банка")
System(callCenter, "Система кол-центра", "Система внутреннего кол-центра банка")
System(partnerCallCenter, "Система партнерского кол-центра", "Система партнерского кол-центра")
System(SMSGateway, "СМС-шлюз телеком-оператора", "Направляет СМС уведомления пользователям")
' Взаимодействия
user ..> site: "Использует"
site ..> ABS: "Запрашивает актуальные ставки, передает заявки на создание депозитов"
ABS .up.> site: "Передает маркетинговую информацию"

site .left.> ebank: "Перенаправляет клиента для авторизации"

user .down.> ebank: "Использует"
ebank .down.> ABS: "Запрашивает актуальные ставки, передает информацию по платежам и заявкам на депозиты"
ABS .up.> ebank: "Передает маркетинговую информацию, данные по депозитным и кредитным счетам"

ebank .down.> SMSGateway: "Отправляет коды по СМС"

backManager ..> ABS: "Управляет кредитными и дебетовыми процессами"
frontManager ..> ABS: "Работает с обращениями клиентов офиса"

ABS <.. callCenter: "Передает информацию по обращениям"
callCenter <.. operator: "Заводит обращения"
partnerCallCenter <.. partnerOperator: "Заводит обращения"
ABS <.. partnerCallCenter: "Передает информацию по обращениям"

ABS ..> SMSGateway: "Отправляет уведомления"

@enduml